HAFunctions/HAFunctions.UI/Models/AssemblyCompileResult.cs
using System.Reflection;
using HAFunctions.UI.Services;
using Microsoft.CodeAnalysis;

namespace HAFunctions.UI.Models;

public class AssemblyCompileResult
{
    public Assembly? Assembly { get; set; }
    public bool Success { get; set; }
    public FunctionCompilerDiagnostic[] Diagnostics { get; set; } = new FunctionCompilerDiagnostic[0];
}

HAFunctions/HAFunctions.UI/Models/ErrorViewModel.cs
namespace HAFunctions.UI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

HAFunctions/HAFunctions.UI/Models/FunctionCompilerDiagnostic.cs
using System.Reflection;
using System.Text.Json.Serialization;
using Microsoft.CodeAnalysis;

namespace HAFunctions.UI.Models;

public class FunctionCompilerDiagnostic
{
    [JsonPropertyName("severity")]
    public string Severity { get; set; }
    [JsonPropertyName("message")]
    public string Message { get; set; }
    [JsonPropertyName("from")]
    public FileLinePosition From { get; set; }
    [JsonPropertyName("to")]
    public FileLinePosition To { get; set; }

    public override string ToString()
    {
        return $"{From} - {To} {Severity}: {Message}";
    }
}

public class FileLinePosition
{
    [JsonPropertyName("line")]
    public int Line { get; set; }
    [JsonPropertyName("ch")]
    public int Character { get; set; }

    public override string ToString()
    {
        return $"L{Line},{Character}";
    }
}

HAFunctions/HAFunctions.UI/Models/HAFunctionAssemblyLoadContext.cs
using System.Reflection;
using System.Runtime.Loader;

namespace HAFunctions.UI.Models;

public class HAFunctionAssemblyLoadContext : AssemblyLoadContext
{
    private AssemblyDependencyResolver _resolver;
    public bool Unloaded { get; set; }

    public HAFunctionAssemblyLoadContext() : base(isCollectible: true)
    {
        _resolver = new AssemblyDependencyResolver(Path.GetDirectoryName(typeof(object).Assembly.Location));
        Unloading += (s) => Unloaded = true;
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
        if (assemblyPath != null)
        {
            return LoadFromAssemblyPath(assemblyPath);
        }
        return null;
    }

    protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
    {
        string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
        if (libraryPath != null)
        {
            return LoadUnmanagedDllFromPath(libraryPath);
        }
        return IntPtr.Zero;
    }
}

HAFunctions/HAFunctions.UI/Models/UnableToCreateInstanceException.cs
namespace HAFunctions.UI.Models;

[Serializable]
public class UnableToCreateInstanceException : Exception
{
    public Exception[] InnerExceptions { get; set; }
    public UnableToCreateInstanceException(Exception[] innerExceptions)
    {
        InnerExceptions = innerExceptions;
    }

    public UnableToCreateInstanceException(string? message, Exception[] innerExceptions = null) : base(message)
    {
        InnerExceptions = innerExceptions;
    }
}

HAFunctions/HAFunctions.UI/Controllers/FunctionsController.cs
using Microsoft.AspNetCore.Mvc;
using HAFunctions.UI.Models;
using HAFunctions.UI.Services;
using HAFunctions.Shared.Logging;
using HAFunctions.Shared.Models;
using HAFunctions.Shared.Services;

namespace HAFunctions.UI.Controllers;

public class FunctionsController : Controller
{
    private readonly ILogger<FunctionsController> _logger;
    private readonly FunctionHostService _functionHost;
    private readonly FunctionCompiler _compiler;
    public FunctionsController(ILogger<FunctionsController> logger, FunctionCompiler compiler, FunctionHostService functionHost)
    {
        _logger = logger;
        _compiler = compiler;
        _functionHost = functionHost;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        return View(await _functionHost.GetFunctionsAsync());
    }

    [HttpGet]
    public IActionResult New()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> New([Bind("FileName,Code")] FunctionModel model)
    {
        var FunctionCode = System.IO.File.ReadAllText("wwwroot/StartingFunction.cs.txt");
        model.Code = FunctionCode;

        await _functionHost.AddFunction(model);

        return RedirectToAction("Edit", new { file = model.FileName }); ;
    }

    [HttpGet]
    public async Task<IActionResult> Edit(string file)
    {
        var functions = await _functionHost.GetFunctionsAsync();
        return View(functions.FirstOrDefault(f => f.FileName == file));
    }

    [HttpGet]
    public async Task<IActionResult> Log(string file)
    {
        var functions = await _functionHost.GetFunctionsAsync();
        var model = functions.FirstOrDefault(f => f.FileName == file);
        if (model != null)
        {
            var logs = await _functionHost.GetLogsAsync(file);
            return View("/Views/System/Logs.cshtml", logs);
        }
        else
        {
            return NotFound();
        }
    }

    [HttpPost()]
    public async Task<IActionResult> Edit([Bind("FileName,Code")] FunctionModel model)
    {
        var functions = await _functionHost.GetFunctionsAsync();
        var fileModel = functions.FirstOrDefault(f => f.FileName == model.FileName);

        if (fileModel == null)
            return NotFound();

        await _functionHost.UpdateFunction(model);

        return RedirectToAction(nameof(Edit), new { file = fileModel.FileName });
    }

    [HttpGet]
    public async Task<IActionResult> Delete(string file)
    {
        var functions = await _functionHost.GetFunctionsAsync();
        var fileModel = functions.FirstOrDefault(f => f.FileName == file);
        return View(fileModel);
    }

    [HttpPost]
    public async Task<IActionResult> Delete([Bind("FileName,Code")] FunctionModel model)
    {
        var functions = await _functionHost.GetFunctionsAsync();
        var fileModel = functions.FirstOrDefault(f => f.FileName == model.FileName);

        if (fileModel == null)
            return NotFound();

        await _functionHost.DeleteFunction(model);

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public IActionResult TryCompile([FromBody] FunctionModel model)
    {
        var result = _compiler.CompileFunctionCode(model.Code, null, false);
        return new JsonResult(result);
    }
}

HAFunctions/HAFunctions.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HAFunctions.UI.Models;
using HAFunctions.Shared;
using HAFunctions.UI.Services;
using HAFunctions.Shared.Models;

namespace HAFunctions.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly FunctionHostService _functionHost;

    public HomeController(ILogger<HomeController> logger, FunctionHostService functionHost)
    {
        _logger = logger;
        _functionHost = functionHost;
    }

    public async Task<IActionResult> Index()
    {
        FunctionTracesModel traces = await _functionHost.GetFunctionTracesAsync();
        return View(traces);
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

HAFunctions/HAFunctions.UI/Controllers/SystemController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HAFunctions.Shared.Logging;
using HAFunctions.UI.Services;

namespace HAFunctions.UI.Controllers;

public class SystemController : Controller
{
    private readonly ILogger<SystemController> _logger;
    private readonly FunctionHostService _functionHost;

    public SystemController(ILogger<SystemController> logger, FunctionHostService functionHost)
    {
        _logger = logger;
        _functionHost = functionHost;
    }

    [HttpGet("Logs")]
    public async Task<IActionResult> Logs()
    {
        return View(await _functionHost.GetSystemLogsAsync());
    }
}

HAFunctions/HAFunctions.UI/Views/Functions/Delete.cshtml
@using HAFunctions.Shared
@model HAFunctions.Shared.Models.FunctionModel
@{
    ViewData["Title"] = "Delete Function";
}

@section Header 
{

}
@{
    var item = Model;
    var Index = 0;
}



<p>Are you sure you want to delete this function?</p>
<form id="Delete" asp-action="Delete" class="form-inline">
    <input type="hidden" asp-for="FileName" />
    <a asp-action="Index" class="btn btn-primary">No, go back</a>
    <button type="submit" class="btn btn-danger">Yes, delete</button>
</form>

<div class="accordion mt-4" id="accordion-@Index">
    <div class="accordion-item">
        <h2 class="accordion-header" id="heading-@Index">
            <button class="accordion-button bg-homeassistant text-light" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@Index" aria-expanded="false" aria-controls="collapse-@Index">
                <img src="~/img/ha_function_file.svg" height="40" class="me-2" />@item.FileName
            </button>
        </h2>
        <div id="collapse-@Index" class="accordion-collapse collapse show" aria-labelledby="heading-@Index" data-bs-parent="#accordion-@Index">
            <div class="accordion-body d-flex flex-column-reverse flex-md-row">
                <div class="flex-grow-1 flex-shrink-1">
                    <p><strong>The following methods with trigger attributes were detected in the file:</strong></p>
                    @foreach (var method in item.DefinedFunctionModels)
                    {
                        <p><code class="text-dark">
                        @foreach(var trigger in method.Attributes)
                        {
                            <span class="ha-function-bracket">@Html.Raw("[")</span><span class="ha-function-type">@(trigger.Name)</span>@Html.Raw("<span class=\"ha-function-methodname\">(</span>")
                            @for(var i = 0; i < trigger.Parameters.Count; i++)
                            {
                                var a = trigger.Parameters[i];
                                @Html.Raw($"{a.Name}:") <span class="ha-function-string">@Html.Raw($"{a.Value?.ToString()}")</span>if(i+1 < trigger.Parameters.Count){@Html.Raw(", ")}
                            }
                            @Html.Raw(")")<span class="ha-function-bracket">@Html.Raw("]")</span><br/>
                        }
                        <span class="ha-function-type">@method.ReturnType.GetTypeName()</span> <span class="ha-function-methodname">@method.Name</span><span class="ha-function-bracket">(</span>@foreach(var param in @method.Parameters) {<span class="ha-function-type">@param.Type.GetTypeName()</span> @param.Name if(param != method.Parameters.LastOrDefault()) {<span>,</span>}}<span class="ha-function-bracket">) @Html.Raw("{")</span> ... <span class="ha-function-bracket">@Html.Raw("}")</span></code></p>
                    }
                </div>               
            </div>
        </div>
    </div>
</div>

@section Scripts
{
<script src="~/lib/codemirror/lib/codemirror.js"></script>
<script src="~/lib/codemirror/mode/clike/clike.js"></script>
<script src="~/lib/codemirror/addon/lint/lint.js"></script>
<script src="~/js/csharp-lint.js" ></script>
<script>
    var objectivecEditor = CodeMirror.fromTextArea(document.getElementById("Code"), {
        lineNumbers: true,
        matchBrackets: true,
        mode: "text/x-csharp",
        gutters: ["CodeMirror-lint-markers"],
        lint: true,
        getAnnotations: function(text) {
            var found = [];
            found.push({ from: 1, to: 2, message: "This is fucked up" });
            return found;
        }
    });
    $('#Code').removeClass("d-none");
</script>
}

HAFunctions/HAFunctions.UI/Views/Functions/Edit.cshtml
@model HAFunctions.Shared.Models.FunctionModel
@{
    ViewData["Title"] = "Edit Functions";
    Layout = "/Views/Shared/_LayoutFullscreen.cshtml";
}

@section Header 
{
    <style>
        .CodeMirror {
            height:100%;
        }
    </style>
}

@section Navbar
{
    <button type="submit" form="Edit" class="btn btn-danger">Save</button>
}
<form id="Edit" asp-action="Edit" class="form-inline">
    <input type="hidden" asp-for="FileName" />
    <textarea class="d-none" asp-for="Code"></textarea>
</form>

@section Scripts
{
<script src="~/lib/codemirror/lib/codemirror.js"></script>
<script src="~/lib/codemirror/mode/clike/clike.js"></script>
<script src="~/lib/codemirror/addon/lint/lint.js"></script>
<script src="~/js/csharp-lint.js" ></script>
<script>
    document.addEventListener('keydown', e => {
        if (e.ctrlKey && e.key === 's') {
            // Prevent the Save dialog to open
            e.preventDefault();
            // Place your code here
            console.log('CTRL + S');
            $('#Edit').submit();
        }
    });
    var objectivecEditor = CodeMirror.fromTextArea(document.getElementById("Code"), {
        lineNumbers: true,
        matchBrackets: true,
        mode: "text/x-csharp",
        gutters: ["CodeMirror-lint-markers"],
        lint: true,
        getAnnotations: function(text) {
            var found = [];
            found.push({ from: 1, to: 2, message: "This is fucked up" });
            return found;
        }
    });
    $('#Code').removeClass("d-none");
</script>
}

HAFunctions/HAFunctions.UI/Views/Functions/Index.cshtml
@using HAFunctions.Shared
@model IEnumerable<HAFunctions.Shared.Models.FunctionModel>
@{
    ViewData["Title"] = "Functions";

}

@section Navbar
{
    <a class="btn btn-danger" asp-action="New">New Function</a>
}

@for(var Index = 0; Index < Model.Count(); Index++)
{
    var item = Model.ElementAt(Index);
    <div class="accordion mt-4" id="accordion-@Index">
        <div class="accordion-item">
            <h2 class="accordion-header" id="heading-@Index">
                <button class="accordion-button bg-homeassistant text-light" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@Index" aria-expanded="false" aria-controls="collapse-@Index">
                    <img src="~/img/ha_function_file.svg" height="40" class="me-2" />@item.FileName
                </button>
            </h2>
            <div id="collapse-@Index" class="accordion-collapse collapse @(item == Model.First() ? "show" : "")" aria-labelledby="heading-@Index" data-bs-parent="#accordion-@Index">
                <div class="accordion-body d-flex flex-column-reverse flex-md-row">
                    <div class="flex-grow-1 flex-shrink-1">
                        <p><strong>The following methods with trigger attributes were detected in the file:</strong></p>
                        @foreach (var method in item.DefinedFunctionModels)
                        {
                            <p><code class="text-dark">
                            @foreach(var trigger in method.Attributes)
                            {
                                <span class="ha-function-bracket">@Html.Raw("[")</span><span class="ha-function-type">@(trigger.Name)</span>@Html.Raw("<span class=\"ha-function-methodname\">(</span>")
                                @for(var i = 0; i < trigger.Parameters.Count; i++)
                                {
                                    var a = trigger.Parameters[i];
                                    @Html.Raw($"{a.Name}:") <span class="ha-function-string">@Html.Raw($"{a.Value?.ToString()}")</span>if(i+1 < trigger.Parameters.Count){@Html.Raw(", ")}
                                }
                                @Html.Raw(")")<span class="ha-function-bracket">@Html.Raw("]")</span><br/>
                            }
                            <span class="ha-function-type">@method.ReturnType.GetTypeName()</span> <span class="ha-function-methodname">@method.Name</span><span class="ha-function-bracket">(</span>@foreach(var param in @method.Parameters) {<span class="ha-function-type">@param.Type.GetTypeName()</span> @param.Name if(param != method.Parameters.LastOrDefault()) {<span>,</span>}}<span class="ha-function-bracket">) @Html.Raw("{")</span> ... <span class="ha-function-bracket">@Html.Raw("}")</span></code></p>
                        }
                    </div>
                    <div class="actions d-flex flex-column">
                        <a class="btn btn-primary mb-2" asp-action="Edit" asp-route-file="@item.FileName">Edit</a>
                        <a class="btn btn-info mb-2" asp-action="Log" asp-route-file="@item.FileName">Logs</a>
                        <a class="btn btn-danger mb-2" asp-action="Delete" asp-route-file="@item.FileName">Delete</a>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
}

HAFunctions/HAFunctions.UI/Views/Functions/New.cshtml
@model HAFunctions.Shared.Models.FunctionModel
@{
    ViewData["Title"] = "Create new function";
}

@section Navbar
{
    <button type="submit" form="New" class="btn btn-danger">Save</button>
}
<h4>New Function</h4>
<hr/>
<form id="New" asp-action="New" class="form">
    <label for="FileName" class="form-label">File Name</label>
    <input type="text" class="form-control" asp-for="FileName"/>
</form>

HAFunctions/HAFunctions.UI/Views/Home/Index.cshtml
@using HAFunctions.Shared.Models
@model FunctionTracesModel
@{
    ViewData["Title"] = "Home Page";
}

<h4>Dashboard</h4>
<hr />

<div class="row d-flex m-2 m-sm-0 justify-content-around">
    <div class="card col-12 col-sm-2 me-sm-1 mb-2 shadow bg-success text-light">
        <div class="card-body">
            <p class="mb-0 text-end"><span class="dashboard-text-large">@($"{Model.AverageRunDuration:0.00}")</span> ms
            </p>
            <p class="mb-0 text-end">Avg. Execution Time</h5>
        </div>
    </div>
    <div class="card col-12 col-sm-2 me-sm-1 mb-2 shadow bg-info text-light">
        <div class="card-body">
            <p class="mb-0 text-end"><span class="dashboard-text-large">@Model.TotalExecutions</span></p>
            <p class="mb-0 text-end">Total Executions</h5>
        </div>
    </div>
    <div class="card col-12 col-sm-2 me-sm-1 mb-2 shadow bg-success text-light">
        <div class="card-body">
            <p class="mb-0 text-end"><span class="dashboard-text-large">@Model.TotalSuccessfulExecutions</span></p>
            <p class="mb-0 text-end">Successful Executions</h5>
        </div>
    </div>
    <div class="card col-12 col-sm-2 me-sm-1 mb-2 shadow bg-danger text-light">
        <div class="card-body">
            <p class="mb-0 text-end"><span class="dashboard-text-large">@Model.TotalFailedExecutions</span></p>
            <p class="mb-0 text-end">Failed Executions</h5>
        </div>
    </div>
    <div class="card col-12 col-sm-2 me-sm-1 mb-2 shadow bg-danger text-light">
        <div class="card-body">
            <p class="mb-0 text-end"><span class="dashboard-text-large">@($"{Model.FailureRate:0.00}")</span>%</p>
            <p class="mb-0 text-end">Failure Rate</h5>
        </div>
    </div>
</div>
<div class="row d-flex justify-content-around">
    <div class="mt-4">
        <div class="card shadow">
            <div class="card-header">
                Summary by Function File
            </div>
            <div class="card-body ps-0 pe-0 pt-0 overflow-scroll">
                <table class="table w-100">
                    <thead>
                        <tr class="text-end">
                            <th class="text-start">File</th>
                            <th>Avg. Execution Time</th>
                            <th>Executions</th>
                            <th>Successful</th>
                            <th>Failed</th>
                            <th>Failure Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var fileSummary in Model.SummaryByFunctionFile.OrderByDescending(f =>
                        f.Value.TotalFailedExecutions))
                        {
                            <tr class="text-end">
                                <td class="text-start">@fileSummary.Key</td>
                                <td><strong>@($"{fileSummary.Value.AverageRunDuration:0.00}")</strong> ms</td>
                                <td><strong>@fileSummary.Value.TotalExecutions</strong></td>
                                <td><strong>@fileSummary.Value.TotalSuccessfulExecutions</strong></td>
                                <td><strong>@fileSummary.Value.TotalFailedExecutions</strong></td>
                                <td><strong>@($"{fileSummary.Value.FailureRate:0.00}")</strong> %</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row mt-4 d-flex justify-content-around">
    <div>
        <div class="card shadow">
            <div class="card-header">
                Summary by Function Method
            </div>
            <div class="card-body ps-0 pe-0 pt-0 overflow-scroll">
                <table class="table w-100">
                    <thead>
                        <tr class="text-end">
                            <th class="text-start">Method</th>
                            <th>Avg. Execution Time</th>
                            <th>Executions</th>
                            <th>Successful</th>
                            <th>Failed</th>
                            <th>Failure Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var fileSummary in Model.SummaryByFunctionFileAndMethodName.OrderByDescending(f =>
                        f.Value.TotalFailedExecutions))
                        {
                            <tr class="text-end">
                                <td class="text-start">@fileSummary.Key</td>
                                <td><strong>@($"{fileSummary.Value.AverageRunDuration:0.00}")</strong> ms</td>
                                <td><strong>@fileSummary.Value.TotalExecutions</strong></td>
                                <td><strong>@fileSummary.Value.TotalSuccessfulExecutions</strong></td>
                                <td><strong>@fileSummary.Value.TotalFailedExecutions</strong></td>
                                <td><strong>@($"{fileSummary.Value.FailureRate:0.00}")</strong> %</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

HAFunctions/HAFunctions.UI/Views/Shared/_HeaderContent.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - HAFunctions</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css" />
<link rel="stylesheet" href="~/lib/codemirror/lib/codemirror.css"/>
<link rel="stylesheet" href="~/lib/codemirror/addon/lint/lint.css"/>
<link rel="stylesheet" href="~/css/site.css"/>

HAFunctions/HAFunctions.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="width:100%; height: 100%;">
<head>
    <partial name="_HeaderContent" />
    @RenderSection("Header", required: false)
</head>
<body style="width:100%; height: 100%; margin:0;" class="d-flex flex-column">
    <header class="flex-shrink-0 flex-grow-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-homeassistant border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <partial name="_NavbarContent" />
                @RenderSection("Navbar", required: false)
            </div>
        </nav>
    </header>
    <div class="d-flex flex-column flex-shrink-1 flex-grow-1">
        <div class="flex-grow-1 flex-shrink-1">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

        <footer class="border-top footer-flex flex-grow-0 flex-shrink-0 text-muted">
            <div class="container">
                Footer!
            </div>
        </footer>
    </div>
    <partial name="_Scripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HAFunctions/HAFunctions.UI/Views/Shared/_LayoutFullscreen.cshtml
<!DOCTYPE html>
<html lang="en" style="width:100%; height: 100%;">
<head>
    <partial name="_HeaderContent" />
    @RenderSection("Header", required: false)
</head>
<body style="width:100%; height: 100%; margin:0;" class="d-flex flex-column">
    <header class="flex-shrink-0 flex-grow-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-homeassistant border-bottom box-shadow">
            <div class="container-fluid">
                <partial name="_NavbarContent" />
                @RenderSection("Navbar", required: false)
            </div>
        </nav>
    </header>
    <div class="d-flex flex-column flex-shrink-1 flex-grow-1">
        <main role="main" class="flex-grow-1 flex-shrink-1">
            @RenderBody()
        </main>

        <footer class="border-top footer-flex flex-grow-0 flex-shrink-0 text-muted">
            <div class="container">
                Footer!
            </div>
        </footer>
    </div>
    <partial name="_Scripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HAFunctions/HAFunctions.UI/Views/Shared/_NavbarContent.cshtml
<a class="navbar-brand" href="~/Home/Index"><img src="~/img/ha_functions.svg" height="40"/><span>HAFunctions</span></a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1 text-light">
        <li class="nav-item">
            <a class="nav-link" href="~/Home/Index">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Functions" asp-action="Index">Functions</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="systemDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                System
            </a>
            <ul class="dropdown-menu" aria-labelledby="systemDropdown">
                <li><a class="dropdown-item" asp-action="Logs" asp-controller="System">Logs</a></li>
            </ul>
        </li>
    </ul>
</div>

HAFunctions/HAFunctions.UI/Views/Shared/_Scripts.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/fontawesome-free/js/all.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

HAFunctions/HAFunctions.UI/Views/System/Logs.cshtml
@using HAFunctions.Shared.Logging
@model IEnumerable<InMemoryLogEntry>
@{
    ViewData["Title"] = "System Logs";
}

<div class="card bg-dark text-light overflow-scroll p-2">
    <table>
        @foreach (var entry in Model)
        {
            <tr>
                <td class="text-nowrap pe-1">
                    @Html.DisplayFor(item => entry.Time)
                </td>
                <td class="text-nowrap pe-1">
                    @Html.DisplayFor(item => entry.Source)
                </td>
                <td class="text-nowrap pe-1 @entry.BootstrapClass">
                    @Html.DisplayFor(item => entry.Severity)
                </td>
                <td class="text-nowrap pe-1">
                    @Html.DisplayFor(item => entry.Message)
                </td>
            </tr>
        }
    </table>
</div>